name: daily_notification_sender
description: A command-line tool to send daily notifications via OneSignal.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  supabase_flutter: ^2.5.3
  onesignal_flutter: ^5.1.8
  intl: ^0.18.1
